// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoVwmGTA4u6t9L5vdv6LUnbJJ4rQEfs5A',
    appId: '1:1026728958360:web:02aa389838151d18f5b3ed',
    messagingSenderId: '1026728958360',
    projectId: 'cityguard-53367',
    authDomain: 'cityguard-53367.firebaseapp.com',
    storageBucket: 'cityguard-53367.firebasestorage.app',
    measurementId: 'G-SJSTXEQ4D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP6sqOCyna10x__VibmMZt95XdI4RESpU',
    appId: '1:1026728958360:android:c9f7ea1269739934f5b3ed',
    messagingSenderId: '1026728958360',
    projectId: 'cityguard-53367',
    storageBucket: 'cityguard-53367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1SjbtXxsR7GtU0-MyOwvRkQMERLvVFsk',
    appId: '1:1026728958360:ios:1f49da5896b4793df5b3ed',
    messagingSenderId: '1026728958360',
    projectId: 'cityguard-53367',
    storageBucket: 'cityguard-53367.firebasestorage.app',
    iosBundleId: 'com.example.towncare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1SjbtXxsR7GtU0-MyOwvRkQMERLvVFsk',
    appId: '1:1026728958360:ios:1f49da5896b4793df5b3ed',
    messagingSenderId: '1026728958360',
    projectId: 'cityguard-53367',
    storageBucket: 'cityguard-53367.firebasestorage.app',
    iosBundleId: 'com.example.towncare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoVwmGTA4u6t9L5vdv6LUnbJJ4rQEfs5A',
    appId: '1:1026728958360:web:7113da6dd1e21e35f5b3ed',
    messagingSenderId: '1026728958360',
    projectId: 'cityguard-53367',
    authDomain: 'cityguard-53367.firebaseapp.com',
    storageBucket: 'cityguard-53367.firebasestorage.app',
    measurementId: 'G-54ESZNQ4W8',
  );
}
